//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZadaniaDomowe
    {
        public int ID { get; set; }
        public Nullable<int> KlasaID { get; set; }
        public Nullable<int> UczeńID { get; set; }
        public Nullable<System.DateTime> DataZakończenia { get; set; }
        public Nullable<System.DateTime> DataOddania { get; set; }
        public Nullable<int> NauczycielID { get; set; }
        public string Opis { get; set; }
    
        public virtual Klasy Klasy { get; set; }
        public virtual Nauczyciele Nauczyciele { get; set; }
        public virtual Uczniowie Uczniowie { get; set; }
    }
}
